import type { Metadata } from "next";
import { Montserrat, Raleway } from "next/font/google";
import "./globals.css";

const montserratBlack = Montserrat({
  variable: "--font-montserrat-black",
  subsets: ["latin"],
});

const ralewrayRegular = Raleway({
  variable: "--font-raleway-regular",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Amusement Park - Next.js",
  description: "Generated by create next app",
  authors: {
    name: "Jason Duquenne"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${montserratBlack.variable} ${ralewrayRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
